backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "background"
    label: "Background"
    files:
      - file: "src/content/background/index.md"
        label: "Background Content"
        name: "content"
        fields:
          - {label: "Content Key", name: "contentKey", widget: hidden, default: "background-content"}
          - {label: "Media File", name: media, widget: file}
          - {label: "Link", name: link, widget: string}
          - {label: "Background Title", name: title, widget: string}
          - {label: "Button Text", name: buttonText, widget: string, default: "Watch Video"}
          - label: "Music Links"
            name: musicLinks
            widget: list
            fields:
              - {label: "Type", name: type, widget: select, options: ["spotify", "apple", "youtube", "amazon"]}
              - {label: "Link", name: link, widget: string}
            required: false

  - name: "socialLinks"
    label: "Social Links"
    folder: "src/content/social-links"
    fields:
      - {label: "Content Key", name: "contentKey", widget: "hidden", default: "social-links"}
      - {label: "Index", name: "index", widget: "hidden"}
      - {label: "Icon", name: "icon", widget: hidden}
      - {label: "Title", name: "title", widget: string}
      - {label: "Link", name: "link", widget: string}

  - name: "posts"
    label: "Posts"
    folder: "src/pages/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "post-detail"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Image (leave blank if you are adding a video)", name: image, required: false, widget: file, default: ""}
      - {label: "Video Link (leave blank if you are adding an image)", name: "link", widget: "string", required: false, default: ""}
      - {label: "Section", name: "section", widget: "select", options: ["music", "choreography", "fitness", "travel"], default: "music"}
      - label: "Music Links"
        name: musicLinks
        widget: list
        fields:
          - {label: "Type", name: type, widget: select, options: ["spotify", "apple"]}
          - {label: "Link", name: link, widget: string}
        required: false

  - name: "events"
    label: "Events"
    folder: "src/pages/events"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: hidden, default: "event-detail"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Event Date", name: "date", widget: datetime}
      - {label: "Description", name: "description", widget: "text", required: false}
      - label: "Photos"
        name: photos
        widget: list
        fields:
          - {label: "Photo", name: "photo", widget: image}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/choreography/index.md"
        label: "Choreography"
        name: "choreography"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "choreography-page"}
          - {label: "Index", name: "index", widget: "hidden", default: 1}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Post Limit", name: "limit", widget: number}

      - file: "src/pages/music/index.md"
        label: "Music"
        name: "music"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "music-page"}
          - {label: "Index", name: "index", widget: "hidden", default: 0}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Post Limit", name: "limit", widget: number}

      - file: "src/pages/fitness/index.md"
        label: "Fitness"
        name: "fitness"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "fitness-page"}
          - {label: "Index", name: "index", widget: "hidden", default: 2}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Post Limit", name: "limit", widget: number}
      - file: "src/pages/events/index.md"
        label: "Events"
        name: "events"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "events-page"}
          - {label: "Index", name: "index", widget: "hidden", default: 3}
          - label: "Event"
            name: "event"
            widget: list
            fields:
              - {label: "Event Name", name: "name", widget: string}
              - {label: "Event Date", name: "date", widget: datetime}
              - label: "Photos"
                name: "photos"
                widget: list
                fields:
                  - {label: "Photo", name: "photo", widget: file}

      - file: "src/pages/travel/index.md"
        label: "Travel"
        name: "travel"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "travel-page"}
          - {label: "Index", name: "index", widget: "hidden", default: 5}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Post Limit", name: "limit", widget: number}
      - file: "src/pages/contact/index.md"
        label: "Contact"
        name: "contact"
        fields:
          - {label: "Template Key", name: "templateKey", widget: hidden, default: "contact-page"}
          - {label: "Index", name: "index", widget: hidden, default: 4}
          - label: "Contact categories"
            name: "categories"
            widget: list
            fields:
              - {label: "Category Name", name: "name", widget: string}
              - label: "Contacts"
                name: contacts
                widget: list
                fields:
                  - {label: "Contact Name", name: "name", widget: string}
                  - {label: "Email", name: "email", widget: string}
                  - {label: "Phone Number", name: "phone", widget: string, required: false}
